[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_raffle = "Raff1eFXd6RxKHKvXNbS8JkPLh3WYw8HXfwGcyuLvjCQ"

[programs.devnet]
solana_raffle = "Raff1eFXd6RxKHKvXNbS8JkPLh3WYw8HXfwGcyuLvjCQ"

[programs.mainnet]
solana_raffle = "Raff1eFXd6RxKHKvXNbS8JkPLh3WYw8HXfwGcyuLvjCQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"