[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raffle = "9cxRrfmbrS2iL1XmiqRsbPDEneweaKm7FWNmnjGdmo8J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/babes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
